name = "cloudflare-docker-proxy"
compatibility_date = "2023-12-01"

[dev]
ip = "0.0.0.0"
port = 8787
local_protocol = "http"

[env.dev.vars]
MODE = "debug"
TARGET_UPSTREAM = "https://registry-1.docker.io"

[env.production]
name = "docker"
routes = [
  { pattern = "docker.fastss5.com", custom_domain = true },
  { pattern = "quay.fastss5.com", custom_domain = true },
  { pattern = "gcr.fastss5.com", custom_domain = true },
  { pattern = "k8s-gcr.fastss5.com", custom_domain = true },
  { pattern = "k8s.fastss5.com", custom_domain = true },
  { pattern = "ghcr.fastss5.com", custom_domain = true },
  { pattern = "cloudsmith.fastss5.com", custom_domain = true },
  { pattern = "ecr.fastss5.com", custom_domain = true }
]

[env.production.vars]
MODE = "production"
TARGET_UPSTREAM = ""

[env.staging]
name = "docker-staging"
route = { pattern = "docker-staging.fastss5.com", custom_domain = true }

[env.staging.vars]
MODE = "staging"
TARGET_UPSTREAM = ""
